version: "3.7"

services:
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - "db"
    depends_on:
      - "db"

  db:
    image: postgres
    container_name: rentx-postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx

volumes:
  pgdata:
    driver: local

